# This configuration was used Ebert to review the axelclark/ex338 repository
# on 75820074a0a4065736db42f4f4108e9c01a4e2e8.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- priv/repo
- test
- deps
- assets/node_modules
- _build
- .git
- web/static

