language: elixir
elixir: 1.5.2
otp_release: 20.1
sudo: false

addons:
  postgresql: '9.4'

cache:
  directories:
    - _build
    - deps

env:
  - MIX_ENV=test

script:
  - mix ecto.create
  - mix test --exclude integration

