language: elixir
elixir: 1.4.4
otp_release: 19.3
sudo: false

addons:
  postgresql: '9.4'

cache:
  directories:
    - _build
    - deps

env:
  - MIX_ENV=test

script:
  - mix ecto.create
  - mix test --exclude integration

